env:
  commonjs: true
  es6: true
  node: true
extends:
  - airbnb-base
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
rules: {
  "max-len": ["error", 120, 2],
  "no-async-promise-executor": "off",
  "indent": ["error", 4]
}
